### ISSUE TITLE
Tabris 2.x to 3.x migration

### ISSUE THREAD

**Issue by jumpjack** [eclipsesource/tabris-js#2218]
[This page](https://tabris.com/tabris-decorators-part-2-introducing-tabris-components/) describes changes, but does it exist a tool which analyze my source and lists difference?
How can I "backport" a 3.x script to 2.x to run it on windows?

**Comment by cookieguru** [comment]
There isn't a tool for either of your questions.  You'll need to perform the migrations manually.

**Comment by jumpjack** [comment]
I am trying, with no success: is "tabris-decorators" implemented or not in 2.x? According to documentation it is, but none of these lines  works in developer app for 2.x:

const {ItemPicker, List} = require('tabris-decorators');

import {ItemPicker, List} from 'tabris-decorators';

**Comment by cookieguru** [comment]
You'll want to switch to [the older version](https://github.com/eclipsesource/tabris-decorators/blob/2.x/package.json#L22) which is compatible with the (deprecated) 2.x

**Comment by jumpjack** [comment]
how do I enable it in palyground of developer app 2.x?

**Comment by cookieguru** [comment]
You can access the [legacy playground](https://build.tabris.com/)

**Comment by jumpjack** [comment]
Yes, that's what I'm doing...
I copied my script from new playgorund  to legacy playground, and tabris 2.x raises this errors:

import {ItemPicker, List} from 'tabris-decorators';  --> syntax error, unexpected token import

const {ItemPicker, List} = require('tabris-decorators');  -->  Could not load main module: Error: Cannot find module 'tabris-decorators'

**Comment by jumpjack** [comment]
We are discussing at same time in slackand here... anyway syntax "import from"  works fine in Tabris 3.8.0, but only for "tabris", not for "tabris-decorators"

**Comment by cookieguru** [comment]
> import {ItemPicker, List} from 'tabris-decorators'; --> syntax error, unexpected token import

This isn't es5 syntax.  Only es5 is supported.

> const {ItemPicker, List} = require('tabris-decorators'); --> Could not load main module: Error: Cannot find module 'tabris-decorators'

only the `tabris` package is available on the playground.  You'll need to download [tabris-cli](https://www.npmjs.com/package/tabris-cli) to use the developer app with any other packages or plugins

**Comment by jumpjack** [comment]
It's a pity, in new playground it's available.
So is there any way to debug tabris2/windows apps online, without installing node.js on PC?

**Comment by cookieguru** [comment]
You could install node.js on someone else's computer

**Comment by jumpjack** [comment]
Then I assume the answer is "no, because a bug in playground of 2.x prevents from testing app  in developer app for 2.x"

**Comment by jumpjack** [comment]
Where can I find the source code of the examples of the android developer app for 2.x and for windows developer app?

**Comment by cookieguru** [comment]
> Then I assume the answer is "no, because a bug in playground of 2.x prevents from testing app in developer app for 2.x"

What bug?

**Comment by cookieguru** [comment]
> Where can I find the source code of the examples of the android developer app for 2.x and for windows developer app?

https://github.com/eclipsesource/tabris-js/tree/1f410683f1d52f5fc5557947ffe272c4e5c45eb8/snippets

**Comment by jumpjack** [comment]
> > Where can I find the source code of the examples of the android developer app for 2.x and for windows developer app?
> 
> https://github.com/eclipsesource/tabris-js/tree/1f410683f1d52f5fc5557947ffe272c4e5c45eb8/snippets

These are for 3.x. I'd need the ones for 2.x:

![image](https://user-images.githubusercontent.com/1620953/166162144-13225696-9dd4-46b2-a1e3-b980f7930872.png)

**Comment by jumpjack** [comment]
Specifically, the "input elements" one:

![image](https://user-images.githubusercontent.com/1620953/166162206-18c60312-c676-44b6-a8c1-e2198a556296.png)

**Comment by jumpjack** [comment]
Found in archive:

https://github.com/eclipsesource/tabris-js/blob/f594fbaca6101d792f5e2ca1144dd729d25fd4a6/snippets/input.jsx

**Comment by cookieguru** [comment]
> > > Where can I find the source code of the examples of the android developer app for 2.x and for windows developer app?
> > 
> > 
> > https://github.com/eclipsesource/tabris-js/tree/1f410683f1d52f5fc5557947ffe272c4e5c45eb8/snippets
> 
> These are for 3.x. I'd need the ones for 2.x:

Actually, these are for 2.x.  On GitHub we can [view the list of tagged releases](https://github.com/eclipsesource/tabris-js/releases) and we can see that [the 2.9 release](https://github.com/eclipsesource/tabris-js/releases/tag/v2.9.0) was tagged at 1f410683f1d52f5fc5557947ffe272c4e5c45eb8.  Clicking on that commit hash will allow us to [browse the source code](https://github.com/eclipsesource/tabris-js/tree/1f410683f1d52f5fc5557947ffe272c4e5c45eb8) at that version number.



> Found in archive:
> 
> https://github.com/eclipsesource/tabris-js/blob/f594fbaca6101d792f5e2ca1144dd729d25fd4a6/snippets/input.jsx

Using the same methodology as above we can browse the source at that revision and determine that this commit you found is not for 2.x, it is much newer: it is [from the 3.8 release](https://github.com/eclipsesource/tabris-js/blob/f594fbaca6101d792f5e2ca1144dd729d25fd4a6/package.json#L3)

**Comment by jumpjack** [comment]
I have no idea of how to select a  specific version of a repo, I just looked for "flyer" in the whole repo (a keyword I've seen in the screenshot)  and I found that file...

Anyway, back to the topic,  to back-migrate from 3.x to 2.x, should I convert all the interface declarations from .JS style to .JSX style?

**Comment by cookieguru** [comment]
You can use JS, JSX, TS, or TSX, whichever you prefer
