### ISSUE TITLE
Can't build app using cloud service with cordova plugin

### ISSUE THREAD

**Issue by Gregivy** [eclipsesource/tabris-js#913]
I am trying to put an overlay image on camera view. I have found this plugin https://github.com/donaldp24/CanvasCameraPlugin, but I can't build my app for some reason.

**Comment by cookieguru** [comment]
What errot are you receiving?

**Comment by Gregivy** [comment]
A lot of errors like this one, all connected with some package R
:compileDebugJavaWithJavac/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:87: error: package R does not exist

**Comment by mpost** [comment]
From my understanding the R file that is resolved in that class is the the R `com.keith.canvascameraplugin.R`. When copying the resources from the plugin into your own app the resources are only available under the `R` namespace of your own app (the id as given in your config.xml). That is why you would have to resolve resources by string (package name, qualifier and resource name).

My question would therefore be... does this plugin work in a regular cordova app that does not have the package name `com.keith.canvascameraplugin`?

**Comment by cookieguru** [comment]
I also see this in your `config.xml`:
```xml
 <plugin name="com.keith.cordova.plugin.canvascamera" spec="1.0.1" source="pgb" />
```
I'm not sure how the build service handles the `spec` and `source` attributes.

Perhaps [this one](https://www.npmjs.com/package/com.simetrica.cordova.plugin.canvascamera) on npm (I'm not sure how to handle `-dev`, it might work with just `version="1.0.0"`) or [this one](https://github.com/donaldp24/CanvasCameraPlugin)? 


From [Adding Plugins](https://tabrisjs.com/documentation/latest/build#adding-plugins):
> The online build supports the Cordova <plugin /> tag. This tag allows you to add plugins using an ID, an HTTP or a git URL.

So if you were to remove `source="pgb"` I would expect it to fail completely.

**Comment by mpost** [comment]
Closing this one. Feel free to reopen if you still have problems.
