### ISSUE TITLE
tabris with cordova run

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#289]
I have put tabris.js cordova demo code directly in the www folder. But when I use cordova run, it shows this image.

* I have done everything as cordova support page teachs.
* Does I have to edit index.html or just put tabrisjs exemple code there?

![screenshot_2015-02-19-10-18-55](https://cloud.githubusercontent.com/assets/794195/6266456/32c4a06c-b821-11e4-905a-27c25fdf081a.png)

**Comment by mpost** [comment]
You need to create your cordova application with a package.json inside the www folder. Have a look at the examples like the simple hello world example: https://github.com/eclipsesource/tabris-js/tree/v0.9.1/examples/hello

**Comment by jordiboehmelopez** [comment]
In tabris.js there is no index.html because there is no browser. The javascript is executed in a VM and everything you see is done using native widgets.

**Comment by calebeaires** [comment]
I did this. 

1. Create a project

``` cordova create amigo com.amigo.br Amigo ```

2. On the new project folder, add platform from tabris.js

``` cordova platform add /Users/my-macbook/Downloads/tabris-android ```

3. Deleted default cordova files from www folder
4. Movi files from tabrisjs-master/exemples/cordova to www cordova folder
5. And ``` cordova run```

**Comment by mpost** [comment]
@calebeaires The way you create your project, add the platform and build the app is all correct.

One piece that is missing is the aforementioned `package.json`. Inside the `www` folder you need to add a package.json with the following content. The linked `tabris-0.9.0.min.js` file can be obtained from here: https://tabrisjs.com/download

<code lang="javascript">
{
  "title": "Hello, World!",
  "description": "Tabris.js - Hello, World!",
  "category": "Small Apps",
  "tabris": "tabris-0.9.0.min.js",
  "main": "hello.js"
}
</code>

The `hello.jo` file can be anything you like. For example the hello world example: https://github.com/eclipsesource/tabris-js/blob/v0.9.0/examples/hello/hello.js

**Comment by calebeaires** [comment]
Done. Running and testing!

**Comment by mpost** [comment]
Great to hear. :)

Just in case... You don't have to use the cordova build to get started with tabris.js. You can simply use the tabris.js apps from the app stores and connect to your development server [1] or use the scratchpad [2] on tabrisjs.com.

[1] http://eclipsesource.com/blogs/2015/01/15/fast-dev-roundtrip/
[2] http://eclipsesource.com/blogs/2015/02/06/cloud-javascript-editor-codemirror-tern-for-tabris-js/

**Comment by calebeaires** [comment]
I am testing it with some "cordova plugins" that is important to my apps. I use cordova on them and has implement some important ones: Admob, Notification, Subscribe Google Play Services. Does tabris will work on its own "modules"? 

I have talk about tabris on [this forum] (http://forum.ionicframework.com/t/facebooks-react-native-announced-at-react-js-conf-2015-discussion-thread/17180/8)

**Comment by mpost** [comment]
In general all cordova plugins that don't try to interact with the WebView should work with tabris.js. We haven't tested every plugin out there but if it works with the embedded web view it should work with tabris.js

Regarding your last question... Are you asking whether the tabris.js project is planning on creating new cordova plugins?

**Comment by calebeaires** [comment]
I have tested many cordova plugins with it. It works as aspected. 

About the last question! Will tabris have its own tabris-modules not just widgets and not cordova plugins. I am talking about (sqlite, notification, in-app billing, ads)

**Comment by mpost** [comment]
We are currently relying on cordova to provide support for non-ui related functionality. We do offer a few core properties you will want to use via the device object [1]. The list of features you mentioned above should be met by cordova. Is there anything you are missing or is not up to the task?

[1] https://tabrisjs.com/documentation/device

**Comment by alayii** [comment]
I install tabris as npm module(local), and modify the package.json in hello world example.
{
    "title": "Hello, World!",
    "description": "Tabris.js - Hello, World!",
    "category": "Small Apps",
    "tabris": "tabris.min.js",
    "main": "hello.js"
 }

but it Cannot find module 'tabris', what I missed?

**Comment by hstaudacher** [comment]
As of 0.9.1 you should use the "dependencies" entry in the package.json. See this as an example: https://github.com/eclipsesource/tabris-js/blob/master/examples/animation/package.json

**Comment by alayii** [comment]
ok, figured this out, tabris node module should in the www directory. (
then it works fine and quick. thanks.
